apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  namespace: test-nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:     # 디플로이먼트가 관리할 파드를 찾는 방법.
    matchLabels:      # label 의 app 이름이 nginx 인것을 찾아라.
      app: nginx
  template:
    metadata:
      labels:
        app: nginx		# labels필드를 사용해서 app: nginx 레이블을 붙힘
    spec:
      containers:           # 컨테이너 하나 생성
      - name: nginx			# name 필드의 값 nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Service
  namespace: test-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 8080
    targetPort: 80
